name: Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and test (${{ matrix.safe }}, ${{ matrix.opt }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        safe: [yes, no]
        opt: [O0, O3]

    steps:
      - uses: actions/checkout@v7

      - uses: ManuLinares/setup-c3@v1
        with:
          version: 0.8.3

      - name: Build
        run: c3c build mtk --safe=${{ matrix.safe }} -${{ matrix.opt }}

      - name: Test
        run: c3c test --safe=${{ matrix.safe }} -${{ matrix.opt }}
